### ISSUE TITLE
building in windows

### ISSUE THREAD

**Issue by mehdi200180** [DavidToddMiller/gr-HighDataRate_Modem#2]
Hi. is it possible to build this project (OOT modules) in windows?

**Comment by DavidToddMiller** [comment]
- The goal of this project is to produce actual real-time RF modems with high data rates via GNU Radio flowgraphs and determine the real-time limits of GNU Radio in terms of speed with multi-core PCs. 
           - Maximizing processing speed is essential.
- Based on my experience using a "windows" version of GNU Radio several years ago, the GNU Radio processing speed on windows was at least 50% slower compared to Ubuntu.

Therefore, I have no plans to pursue a windows version for the flowgraphs and OOT blocks in this repository. I intend to stick with Ubuntu.

If in the future, quantitative test results are obtained by someone that demonstrate newer more recent windows versions of GNU Radio approach the same processing speeds one can obtain on a Linux PC, I would reconsider.

A quantitative comparison of GNU Radio performance on Windows versus Linux might be a good idea for a GNU Radio Conference project/paper for someone. :smiley:

**Comment by mehdi200180** [comment]
thanks.
