### ISSUE TITLE
file source problem.

### ISSUE THREAD

**Issue by mehdi200180** [DavidToddMiller/gr-HighDataRate_Modem#3]
when i put the file source block repeat option in no state and demodulate the modulated QPSK file, there are a lot of error at the end of files just before the demodulating process gets finished. can you guess where the problem could be.

**Comment by mehdi200180** [comment]
Hi again. can you answer to my question please?

**Comment by DavidToddMiller** [comment]
If I understand the question:

- For the file source block on the modulation side of the flowgraph, I set the "Repeat" parameter to "No".
- After the file source file completes, the Tx Sink "dongle" block will just transmit a constant Continuous Wave (CW) signal at least for my dongle.
- On the receive side of the flowgraph, an "all ones" CW pattern at that point can not be demodulated (symbol synchronizer requires data transitions to lock).
- One can add a "Freq Sink" block at the output of the "Rx Source" dongle block and see the spectrum transition from "wideband with data" to "CW" when the file source file ends.
